name: Update Prod Server
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: ${{ secrets.PORT }}
      script: whoami
